### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by makrusw2** [Oneledger/protocol#119]
Good day! Could you please clarify how I may run a node and what I need for that?

**Comment by paulwhomer** [comment]
You can run the Docker container that sets up 4 nodes for our chain, 3 for bitcoin and 3 for ethereum. It is a self-contained environment for testing and experimenting with the features. For the upcoming testnet, you will be able run your own node and connect to our public test chain.

**Comment by makrusw2** [comment]
> You can run the Docker container that sets up 4 nodes for our chain, 3 for bitcoin and 3 for ethereum. It is a self-contained environment for testing and experimenting with the features. For the upcoming testnet, you will be able run your own node and connect to our public test chain.

Hello! Where I can check the algorithm in details?
